/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BarGraphData = IDL.Record({
  'categories' : IDL.Vec(IDL.Text),
  'values' : IDL.Vec(IDL.Float64),
});
export const TableData = IDL.Record({
  'rows' : IDL.Vec(IDL.Vec(IDL.Text)),
  'headers' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'fetchBarGraphData' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(BarGraphData)],
      ['query'],
    ),
  'fetchTableData' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(TableData)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BarGraphData = IDL.Record({
    'categories' : IDL.Vec(IDL.Text),
    'values' : IDL.Vec(IDL.Float64),
  });
  const TableData = IDL.Record({
    'rows' : IDL.Vec(IDL.Vec(IDL.Text)),
    'headers' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'fetchBarGraphData' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(BarGraphData)],
        ['query'],
      ),
    'fetchTableData' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(TableData)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };